EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Models/ForgotPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EnvironmentalSustainabilityApp.Models
{
    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Models/ResetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EnvironmentalSustainabilityApp.Models
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password",
            ErrorMessage = "Password and Confirm Password must match")]
        public string ConfirmPassword { get; set; }

        public string Token { get; set; }
    }
}

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Controllers/CarbonFootprintController.cs
using EnvironmentalSustainabilityApp.Models;
using EnvironmentalSustainabilityApp.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EnvironmentalSustainabilityApp.Controllers
{
    public class CarbonFootprintController : Controller
    {
        private readonly ILogger<CarbonFootprintController> _logger;
        private readonly IConfiguration _configuration;
        private DBUtil _dbUtil;
        private readonly UserManager<IdentityUser> _userManager;

        public CarbonFootprintController(ILogger<CarbonFootprintController> logger,
                                         IConfiguration configuration,
                                         UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _configuration = configuration;
            _dbUtil = new DBUtil(_configuration.GetConnectionString("DefaultConnection"));
            _userManager = userManager;
        }

        public async Task<IdentityUser> GetApplicationUser()
        {
            return await _userManager.GetUserAsync(User);
        }

        public async Task<IActionResult> EnergyUsage()
        {
            var currentUser = await GetApplicationUser();
            decimal? carbonFootprintResult = _dbUtil.GetCarbonFootprintByCategory(currentUser.Id, CommonUtil.EnergyUsage);
            bool hasResult = false;

            if (carbonFootprintResult.HasValue)
                hasResult = true;
            else
                carbonFootprintResult = 0;

            ViewBag.CarbonFootprintResult = carbonFootprintResult.ToString();
            ViewBag.HasCarbonFootprintResult = hasResult;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CalculateEnergyFootprint(EnergyUsageViewModel model)
        {
            if (ModelState.IsValid)
            {
                // in kg CO2 per unit
                const double ElectricityEmissionsFactor = 0.309;
                const double GasEmissionsFactor = 0.21;
                const double OilEmissionsFactor = 0.28;
                const double WoodPelletEmissionsFactor = 0.04;
                const double HeatPumpEmissionsFactor = 0.59;
                const double SolarEmissionsFactor = 0;
                const double ElectricHeatingEmissionsFactor = 0.59;
                const double ApplianceEmissionsFactor = 0.1; // in kg CO2 per hour
                const double RenewableEnergyReductionFactor = 0.2; // 20% reduction in emissions
                const int MonthsInYear = 12;
                const int DaysInYear = 365;

                double electricityConsumptionPerMonth = model.ElectricityConsumption;
                string heatingType = model.HeatingType;
                double applianceUsagePerDay = model.ApplianceUsage;
                string renewableEnergy = model.RenewableEnergy;
                int numberOfPeople = model.NumberOfPeople;

                double electricityEmissionsPerYear = electricityConsumptionPerMonth * MonthsInYear * ElectricityEmissionsFactor;

                double heatingFactor = 0;
                double heatingEmissionsPerYear = 0;
                switch (heatingType)
                {
                    case "Gas":
                        heatingFactor = GasEmissionsFactor;
                        break;
                    case "Oil":
                        heatingFactor = OilEmissionsFactor;
                        break;
                    case "WoodPellet":
                        heatingFactor = WoodPelletEmissionsFactor;
                        break;
                    case "HeatPump":
                        heatingFactor = HeatPumpEmissionsFactor;
                        break;
                    case "Solar":
                        heatingFactor = SolarEmissionsFactor;
                        break;
                    case "Electric":
                        heatingFactor = ElectricHeatingEmissionsFactor;
                        break;
                }

                heatingEmissionsPerYear = electricityConsumptionPerMonth * MonthsInYear * heatingFactor;

                double applianceEmissionsPerYear = applianceUsagePerDay * DaysInYear * ApplianceEmissionsFactor;

                if (renewableEnergy == "Yes")
                {
                    electricityEmissionsPerYear *= (1 - RenewableEnergyReductionFactor);
                    heatingEmissionsPerYear *= (1 - RenewableEnergyReductionFactor);
                }

                double totalEmissionsPerYear = electricityEmissionsPerYear + heatingEmissionsPerYear + applianceEmissionsPerYear;
                double carbonFootprintPerPersonPerYear = totalEmissionsPerYear / numberOfPeople;

                var currentUser = await GetApplicationUser();
                _dbUtil.SaveCarbonFootprintByCategory(currentUser.Id, CommonUtil.EnergyUsage, (decimal)carbonFootprintPerPersonPerYear);

                return Ok();
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        public async Task<IActionResult> Transportation()
        {
            var currentUser = await GetApplicationUser();
            decimal? carbonFootprintResult = _dbUtil.GetCarbonFootprintByCategory(currentUser.Id, CommonUtil.Transportation);
            bool hasResult = false;

            if (carbonFootprintResult.HasValue)
                hasResult = true;
            else
                carbonFootprintResult = 0;

            ViewBag.CarbonFootprintResult = carbonFootprintResult.ToString();
            ViewBag.HasCarbonFootprintResult = hasResult;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CalculateTransportationFootprint(TransportationViewModel model)
        {
            if (ModelState.IsValid)
            {
                // in kg CO2 per kilometer
                const double DrivingEmissionsPetrol = 0.54689; 
                const double DrivingEmissionsDiesel = 0.54689;
                const double DrivingEmissionsHybrid = 0.38544;
                const double DrivingEmissionsElectric = 0.177;
                const double DrivingEmissionsOther = 0.563;
                const double FlightEmissionsFactor = 1.206; // (per passenger kilometer)
                const int FlightAverageKm = 1500;
                const double PublicTransportEmissionsFactor = 0.338;
                const int PublicTransportAverageKmPerWeek = 30;
                const int WeeksInYear = 52;

                double kilometersDrivenPerWeek = model.KilometersDriven;
                int flightsTakenPerYear = model.FlightsTaken;
                string fuelType = model.FuelType;
                int numberOfVehicles = model.NumberOfVehicles;
                bool usesPublicTransport = model.UsesPublicTransport;

                double drivingEmissions = 0;
                double fuelEmissionsFactor = 0;
                switch (fuelType)
                {
                    case "Petrol":
                        fuelEmissionsFactor = DrivingEmissionsPetrol;
                        break;
                    case "Diesel":
                        fuelEmissionsFactor = DrivingEmissionsDiesel;
                        break;
                    case "Electric":
                        fuelEmissionsFactor = DrivingEmissionsElectric;
                        break;
                    case "Hybrid":
                        fuelEmissionsFactor = DrivingEmissionsHybrid;
                        break;
                    case "Other":
                        fuelEmissionsFactor = DrivingEmissionsOther;
                        break;
                }

                if (numberOfVehicles != 0)
                    drivingEmissions = (kilometersDrivenPerWeek * WeeksInYear * fuelEmissionsFactor) / numberOfVehicles;

                double flightEmissions = flightsTakenPerYear * FlightAverageKm * FlightEmissionsFactor;

                double publicTransportEmissions = 0;
                if (usesPublicTransport)
                {
                    publicTransportEmissions = PublicTransportAverageKmPerWeek * WeeksInYear * PublicTransportEmissionsFactor;
                }

                double totalEmissions = drivingEmissions + flightEmissions + publicTransportEmissions;

                var currentUser = await GetApplicationUser();
                _dbUtil.SaveCarbonFootprintByCategory(currentUser.Id, CommonUtil.Transportation, (decimal)totalEmissions);

                return Ok();
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        public async Task<IActionResult> FoodAndDiet()
        {
            var currentUser = await GetApplicationUser();
            decimal? carbonFootprintResult = _dbUtil.GetCarbonFootprintByCategory(currentUser.Id, CommonUtil.FoodAndDiet);
            bool hasResult = false;

            if (carbonFootprintResult.HasValue)
                hasResult = true;
            else
                carbonFootprintResult = 0;

            ViewBag.CarbonFootprintResult = carbonFootprintResult.ToString();
            ViewBag.HasCarbonFootprintResult = hasResult;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CalculateFoodAndDietFootprint(FoodAndDietViewModel model)
        {
            if (ModelState.IsValid)
            {
                const double MeatEmissions = 6.7;
                const double VegetarianEmissions = 4.0;
                const double VeganEmissions = 2.0;
                const double OrganicFoodEmissionsReduction = 0.5;
                const int WeeksInYear = 52;

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Views/Home/AdminHome.cshtml
@{
    ViewData["Title"] = "Admin Home";
}

<div style="padding: 20px;">
    <h2 style="text-align: center;">Content Management</h2>
    <div>
        <hr>
        <div class="row">
            <div class="col-md-3" id="content-menu">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item"><a class="nav-link nav-hover active" id="add-new-content" href="#">Add New Content</a></li>
                </ul>
                <div style="margin: 20px 0 5px 0;">Content List:</div>
                <div id="content-list-container" style="max-height: 325px; overflow-y: auto; padding-right: 10px;">
                    <ul id="content-list" class="nav nav-pills flex-column">
                    </ul>
                </div>
            </div>
            <div class="col-md-9" id="content-details" style="padding: 0 80px 0 80px;">
                <form id="content-form" method="post" asp-controller="Home" asp-action="SaveContent">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group" id="panel-img">
                                <label for="ContentImage">Content Image</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="ContentImage" name="ContentImage" accept="image/jpeg, image/jpg, image/png">
                                    <label class="custom-file-label" for="ContentImage">Choose file</label>
                                </div>
                                <div id="image-container" style="max-width: 100%; max-height: 200px; margin-top: 10px;">
                                    <img id="selected-image" src="#" alt="Selected Image" style="max-width: 100%; max-height: 200px; display: none;">
                                    <div id="image-overlay" style="display: none;"></div>
                                    <div id="remove-image-overlay" style="display: none;">
                                        <span id="remove-image-icon">&#10006;</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <label for="ContentTitle">Content Title</label>
                                <input class="form-control" type="text" id="ContentTitle" name="ContentTitle" maxlength="100">
                                <small class="text-muted">Max 100 characters</small>
                            </div>
                            <div class="form-group">
                                <label for="ContentDescription">Content Description</label>
                                <textarea class="form-control" id="ContentDescription" name="ContentDescription" maxlength="300"></textarea>
                                <small class="text-muted">Max 300 characters</small>
                            </div>
                            <div class="form-group">
                                <label for="ContentLink">Content Link</label>
                                <input class="form-control" type="text" id="ContentLink" name="ContentLink">
                            </div>
                            <div class="form-group">
                                <label for="IsContentActive">Is Content Active?</label>
                                <input type="checkbox" id="IsContentActive" name="IsContentActive" checked>
                            </div>
                            <div id="errorMsg" class="alert alert-danger" style="display: none;">
                            </div>
                            <button id="save-content" type="submit" class="btn">Save</button>
                            <button id="delete-content" type="button" class="btn btn-danger" style="background-color: #dc3545 !important; display: none;">Delete</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/content-management.js" asp-append-version="true"></script>
}

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Views/Home/ForgotPassword.cshtml
@model ForgotPasswordViewModel

<div style="padding: 20px;">
    <h2>Forgot Password</h2>
    <hr />
    <div class="row" style="max-width: 40%;">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Views/Home/ForgotPasswordConfirmation.cshtml
<div style="padding: 20px; height: 250px; text-align: center; display: flex; align-items: center;">
    <h4>
        If you have an account with us, we have sent an email with the instructions to reset your password.
    </h4>
</div>

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Views/Home/Index.cshtml
@model IEnumerable<FeaturedContent>
@{
    ViewData["Title"] = "Home Page";
}

@section Styles {
    <style>
        .result-row {
            margin-bottom: 20px;
        }

        .result-col {
        }

        .user-data {
            background-color: rgb(220 245 237);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .card {
            height: 300px;
            border-radius: 30px;
        }

        .col-card {
            padding-left: 5px;
            padding-right: 5px;
        }

        .card-img-fixed {
            max-width: 100%;
            height: 150px;
        }

        .card-text {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-height: 80px;
        }

        img {
            border-radius: 30px 30px 0 0 !important;
        }

        .icon-container {
            display: table;
        }

        .icon-category {
            font-size: 84px;
            color: #6ab04c;
            display: table-cell;
            text-align: center;
            vertical-align: middle;
        }
    </style>
}

<div style="background-color: #bbdccf; margin-top: 50px;">
    @if (ViewBag.AllCategoriesCompleted)
    {
        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-9 text-center" style="max-width: 73.9%;">
                    <h2>Carbon Footprint Results</h2>
                    <p>(in tonnes of CO<sub>2</sub> per year)</p>
                    <div class="row result-row">
                        <div class="col result-col user-data">
                            <canvas id="pieChart" width="400" height="200"></canvas>
                        </div>
                        <div class="col result-col user-data" style="margin-left: 20px;">
                            <p>Based on your answers, your total carbon footprint is<br /><strong>@ViewBag.UserTotalCarbonFootprint tonnes of CO<sub>2</sub> per year</strong>.</p>
                        </div>
                    </div>
                    <div class="row result-row">
                        <div class="col result-col user-data">
                            <canvas id="barChart" width="750" height="300"></canvas>
                        </div>
                    </div>
                    <div class="row result-row">
                        <div class="col result-col user-data">
                            <p><strong>Tips to help you live more sustainably</strong></p>
                            <ol style="text-align: left;">
                                <li>Reduce, Reuse, Recycle: Minimize waste and recycle materials.</li>
                                <li>Conserve Energy: Turn off lights and appliances, use energy-efficient options.</li>
                                <li>Use Water Wisely: Fix leaks, save water, and collect rainwater.</li>
                                <li>Sustainable Transportation: Walk, bike, carpool, or use public transport.</li>
                                <li>Support Sustainable Products: Choose eco-friendly options and buy locally.</li>
                            </ol>
                        </div>
                    </div>
                    <a href="@Url.Action("EnergyUsage", "CarbonFootprint")" class="btn btn-system">Retake Test</a>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.NoneCategoriesCompleted)
    {
        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center">
                    <h2>Start Your Carbon Footprint Test</h2>
                    <p>You haven't completed the carbon footprint test yet</p>
                    <a href="@Url.Action("EnergyUsage", "CarbonFootprint")" class="btn btn-system">Start Test</a>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.SomeCategoriesCompleted)
    {
        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center">
                    <h2>Complete Your Carbon Footprint Test</h2>
                    <p>You haven't completed the carbon footprint test for the following categories:</p>
                    <div class="row">
                        @foreach (var category in ViewBag.CategoriesNotCompleted)
                        {
                            <div class="col">
                                <a href="@Url.Action((string)category.Item2, "CarbonFootprint")" class="btn btn-system">@category.Item1</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    }

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="margin-top: 50px;">
        <ol class="carousel-indicators" style="bottom: -30px;">
            @for (int i = 0; i < Math.Ceiling((double)Model.Count() / 3); i++)
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
            }
        </ol>
        <div class="carousel-inner">
            @for (int i = 0; i < Math.Ceiling((double)Model.Count() / 3); i++)
            {
                <div class="carousel-item @(i == 0 ? "active" : "")">
                    <div class="container">
                        <div class="row justify-content-center">
                            @foreach (var item in Model.Skip(i * 3).Take(3))
                            {
                                if (item.IsContentActive)
                                {
                                    <div class="col-md-3 col-card">
                                        <div class="card mb-3">
                                            @if (!string.IsNullOrEmpty(item.ContentImageFileName))
                                            {
                                                <img src="@Url.Action("GetContentImage", "Home", new { fileName = item.ContentImageFileName })" class="card-img-top img-fluid card-img-fixed" alt="Featured Content Image">
                                            }
                                            else
                                            {
                                                <div class="icon-container">
                                                    <i class="fa fa-leaf icon-category card-img-top img-fluid card-img-fixed"></i>
                                                </div>
                                            }
                                            <div class="card-body">
                                                <h5 class="card-title"><a href="@item.ContentLink" target="_blank" style="color: black;">@item.ContentTitle</a></h5>
                                                <p class="card-text" title="@item.ContentDescription" data-toggle="tooltip" data-placement="top">@item.ContentDescription</p>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" style="z-index: 1;">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" style="z-index: 1;">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

@section Scripts {
    @if (ViewBag.AllCategoriesCompleted)
    {
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-annotation/1.0.2/chartjs-plugin-annotation.min.js"></script>
        <script>
            var whiteColor = 'rgba(255, 255, 255, 1)';
            var purpleColor = 'rgba(176, 38, 250, 0.5)';
            var darkPurpleColor = 'rgba(63, 0, 125, 0.5)';
            var grayColor = 'rgba(146, 152, 201, 0.5)';
            var lightGreenColor = 'rgba(53, 217, 30, 0.5)';
            var darkGreenColor = 'rgba(26, 100, 44, 0.5)';

            var pieCtx = document.getElementById('pieChart').getContext('2d');
            var pieChart = new Chart(pieCtx, {
                type: 'pie',
                data: {
                    labels: @Html.Raw(Json.Serialize(ViewBag.ChartLabels)),
                    datasets: [{
                        data: @Html.Raw(Json.Serialize(ViewBag.ChartDataUser)),
                        backgroundColor: [
                            purpleColor,
                            grayColor,
                            lightGreenColor,
                            darkGreenColor
                        ]
                    }]
                },
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            position: 'right',
                        },
                        title: {
                            display: true,
                            text: 'Carbon Footprint by Category',
                            font: {
                                size: 16
                            }
                        }
                    }
                }
            });

            var barCtx = document.getElementById('barChart').getContext('2d');
            var barChart = new Chart(barCtx, {
                type: 'bar',
                data: {
                    labels: @Html.Raw(Json.Serialize(ViewBag.ChartLabels)),
                    datasets: [{
                        label: 'Your',
                        data: @Html.Raw(Json.Serialize(ViewBag.ChartDataUser)),
                        backgroundColor: purpleColor,
                        borderColor: whiteColor,
                        borderWidth: 2
                    }, {
                        label: 'Average',
                        data: @Html.Raw(Json.Serialize(ViewBag.ChartDataTotalAvg)),
                        backgroundColor: grayColor,
                        borderColor: whiteColor,
                        borderWidth: 2
                    }]
                },
                plugins: [ChartDataLabels],
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    plugins: {
                        title: {
                            display: true,
                            text: 'Your vs. Average Carbon Footprint',
                            font: {
                                size: 16
                            }
                        },
                        datalabels: {
                            anchor: 'end',
                            align: 'top'
                        },
                        annotation: {
                            annotations: [{
                                type: 'line',
                                mode: 'horizontal',
                                scaleID: 'y',
                                value: @Html.Raw(Json.Serialize(ViewBag.UserTotalCarbonFootprint)),
                                borderColor: darkPurpleColor,
                                borderWidth: 3,
                                borderDash: [6, 6],
                                label: {
                                    content: 'Your Total: ' + @Html.Raw(Json.Serialize(ViewBag.UserTotalCarbonFootprint)),
                                    enabled: true,
                                    position: 'start'
                                }
                            }, {
                                type: 'line',
                                mode: 'horizontal',
                                scaleID: 'y',
                                value: @Html.Raw(Json.Serialize(ViewBag.AvgTotalCarbonFootprint)),
                                borderColor: darkGreenColor,
                                borderWidth: 3,
                                borderDash: [6, 6],
                                label: {
                                    content: 'Average Total: ' + @Html.Raw(Json.Serialize(ViewBag.AvgTotalCarbonFootprint)),
                                    enabled: true,
                                    position: 'end'
                                }
                            }]
                        }
                    },
                    scales: {
                        y: {
                            beginAtZero: true,
                            suggestedMax: @Html.Raw(Json.Serialize(Math.Max(ViewBag.UserTotalCarbonFootprint, ViewBag.AvgTotalCarbonFootprint) + 1)),
                            title: {
                                display: true,
                                text: 'Carbon Footprint'
                            }
                        }
                    }
                }
            });

        </script>
    }
}

EnvironmentalSustainabilityApp/EnvironmentalSustainabilityApp/Views/Home/ResetPassword.cshtml
@model ResetPasswordViewModel

<div style="padding: 20px;">
    <h2>Reset Password</h2>
    <hr />
    <div class="row" style="max-width: 40%;">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input asp-for="Token" type="hidden" />
                <input asp-for="Email" type="hidden" />
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Reset</button>
            </form>
        </div>
    </div>
</div>